language: node_js

before_install:
- sudo apt-get -y install openssh-client
- git clone https://github.com/x3kcl/suhr.git
- openssl aes-256-cbc -K $encrypted_edc15e6e3ccc_key -iv $encrypted_edc15e6e3ccc_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add deploy_rsa
- ssh -i deploy_rsa root@naumann.hosting pwd
- nvm install --lts
- npm install -g @ionic/cli
addons:
  apt:
    update: true
  ssh_known_hosts: naumann.hosting
before_script:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
  &
script:
- ionic build --prod --engine=browser --watch=false --release
- cp .htaccess www/
- cp install.sh www/
- tar cjvf www.tar.bz www

deploy:
  - provider: script
    skip_cleanup: true
    script: scp $TRAVIS_BUILD_DIR/www.tar.bz root@naumann.hosting:/root/ 
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ssh -i deploy_rsa root@naumann.hosting tar xjvf /root/www.tar.bz &&
              ssh -i deploy_rsa root@naumann.hosting mv /root/www/install.sh /root/ &&
              ssh -i deploy_rsa root@naumann.hosting chmod +x /root/install.sh &&
              ssh -i deploy_rsa root@naumann.hosting /root/install.sh
    on:
      branch: master